package com.rndworkbench.core.routing;

public enum RoutingReason {
    LOCAL_SELECTED,
    CORPORATE_SELECTED,
    EXTERNAL_SELECTED,
    LOCAL_UNAVAILABLE,
    CORPORATE_UNAVAILABLE,
    EXTERNAL_UNAVAILABLE,
    CORPORATE_SCOPE_NOT_AUTHORIZED,
    CLASSIFICATION_BLOCKS_CORPORATE,
    EXTERNAL_DISABLED_FOR_PILOT,
    CLASSIFICATION_BLOCKS_EXTERNAL,
    EXTERNAL_CONSENT_REQUIRED,
    NO_PERMITTED_ROUTE
}
