package com.rndworkbench.core.autonomy;

public enum ActionKind {
    READ_CONTEXT,
    SEARCH_AND_ANALYZE,
    TRANSCRIBE_AUDIO,
    UPDATE_WORKING_MEMORY,
    CREATE_DRAFT,
    SELECT_MODEL,
    UPDATE_PERSONAL_TASK,
    UPDATE_INTERNAL_MATERIAL,
    CLASSIFY_WORKSPACE_CONTENT,
    RUN_PREAUTHORIZED_AUTOMATION,
    SEND_MESSAGE_OR_EMAIL,
    UPSERT_CALENDAR_EVENT,
    ASSIGN_WORK_ITEM,
    UPSERT_KNOWLEDGE_PAGE,
    EXTERNAL_WRITE,
    DELETE_DATA,
    MASS_OPERATION,
    CHANGE_PERMISSIONS,
    PUBLISH_EXTERNAL,
    IRREVERSIBLE_HIGH_RISK
}
